/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bff/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get banks page composed sections */
        get: operations["getBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get categories page composed sections */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available currencies and default currency for the authenticated user */
        get: operations["getCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get imports page composed sections */
        get: operations["getImports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get investments page composed sections */
        get: operations["getInvestments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overview page composed sections */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search movements, positions, and categories for ⌘K palette */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings page composed sections */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated transactions list with summary sections */
        get: operations["getTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bff/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single transaction detail with import run lookup */
        get: operations["getTransactionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get composed dashboard data for the authenticated user */
        get: operations["data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountOptionResponse: {
            alias?: string;
            cbu?: string;
        };
        AccountRowResponse: {
            alias?: string;
            balance?: components["schemas"]["MoneyView"];
            bankName?: string;
            cbu?: string;
            type?: string;
        };
        ActiveRunResponse: {
            fileName?: string;
            /** Format: int32 */
            processed?: number;
            /** Format: int64 */
            runId?: number;
            /** Format: date-time */
            startedAt?: string;
            status?: string;
            /** Format: int32 */
            total?: number;
        };
        AlertRowResponse: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: int64 */
            id?: number;
            message?: string;
            read?: boolean;
            title?: string;
        };
        ApiResponseAvailableCurrenciesResponse: {
            code?: string;
            data?: components["schemas"]["AvailableCurrenciesResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseBanksBffResponse: {
            code?: string;
            data?: components["schemas"]["BanksBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseCategoriesBffResponse: {
            code?: string;
            data?: components["schemas"]["CategoriesBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseDashboardResponse: {
            code?: string;
            data?: components["schemas"]["DashboardResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseImportsBffResponse: {
            code?: string;
            data?: components["schemas"]["ImportsBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseInvestmentsBffResponse: {
            code?: string;
            data?: components["schemas"]["InvestmentsBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseOverviewBffResponse: {
            code?: string;
            data?: components["schemas"]["OverviewBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseSearchBffResponse: {
            code?: string;
            data?: components["schemas"]["SearchBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseSettingsBffResponse: {
            code?: string;
            data?: components["schemas"]["SettingsBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseTransactionDetailBffResponse: {
            code?: string;
            data?: components["schemas"]["TransactionDetailBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        ApiResponseTransactionsBffResponse: {
            code?: string;
            data?: components["schemas"]["TransactionsBffResponse"];
            message?: string;
            /** Format: int32 */
            status?: number;
            title?: string;
        };
        AvailableCurrenciesResponse: {
            available?: string[];
            default?: string;
        };
        BanksBffResponse: {
            accounts?: components["schemas"]["SectionResponseListAccountRowResponse"];
            cards?: components["schemas"]["SectionResponseListCardRowResponse"];
            cashDistribution?: components["schemas"]["SectionResponseListCompositionSliceResponse"];
            importHealth?: components["schemas"]["SectionResponseListImportHealthRowResponse"];
            kpis?: components["schemas"]["SectionResponseBanksKpisResponse"];
            loans?: components["schemas"]["SectionResponseListLoanRowResponse"];
            paymentCalendar?: components["schemas"]["SectionResponseListCalendarEntryResponse"];
        };
        BanksKpisResponse: {
            /** Format: int32 */
            accountCount?: number;
            cardDebt?: components["schemas"]["MoneyView"];
            loanBalance?: components["schemas"]["MoneyView"];
            totalCash?: components["schemas"]["MoneyView"];
        };
        BreakdownResponse: {
            cash: components["schemas"]["MoneyView"];
            debt: components["schemas"]["MoneyView"];
            investments: components["schemas"]["MoneyView"];
            savings: components["schemas"]["MoneyView"];
        };
        BudgetRowResponse: {
            alertThresholdPct?: number;
            cap?: number;
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            over?: boolean;
            pct?: number;
            spent?: components["schemas"]["MoneyView"];
        };
        CalendarEntryResponse: {
            amount?: components["schemas"]["MoneyView"];
            /** Format: date */
            date?: string;
            kind?: string;
            label?: string;
        };
        CardRowResponse: {
            alias?: string;
            brand?: string;
            cardNumber?: string;
            /** Format: date */
            closingDate?: string;
            /** Format: date */
            dueDate?: string;
            limit?: number;
            used?: components["schemas"]["MoneyView"];
            usedPct?: number;
        };
        CategoriesBffResponse: {
            budgets?: components["schemas"]["SectionResponseListBudgetRowResponse"];
            kpis?: components["schemas"]["SectionResponseCategoriesKpisResponse"];
            rules?: components["schemas"]["SectionResponseListRuleRowResponse"];
            selectedTrend?: components["schemas"]["SectionResponseCategoryTrendResponse"];
        };
        CategoriesKpisResponse: {
            available?: components["schemas"]["MoneyView"];
            /** Format: int32 */
            overBudgetCount?: number;
            pacePct?: number;
            spent?: components["schemas"]["MoneyView"];
        };
        CategoryOptionResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        CategorySpendResponse: {
            amount?: components["schemas"]["MoneyView"];
            /** Format: int64 */
            categoryId?: number;
            name?: string;
            pct?: number;
        };
        CategoryTrendPointResponse: {
            amount?: components["schemas"]["MoneyView"];
            month?: string;
        };
        CategoryTrendResponse: {
            /** Format: int64 */
            categoryId?: number;
            points?: components["schemas"]["CategoryTrendPointResponse"][];
        };
        CommittedPointResponse: {
            amount?: components["schemas"]["MoneyView"];
            month?: string;
        };
        CompositionSliceResponse: {
            amount?: components["schemas"]["MoneyView"];
            label?: string;
            pct?: number;
        };
        CurrencySummary: {
            balance?: string;
            currency?: string;
            totalExpense?: string;
            totalIncome?: string;
        };
        DashboardResponse: {
            activeLoans?: components["schemas"]["SectionResponseListLoan"];
            month?: components["schemas"]["SectionResponseListCurrencySummary"];
            upcomingPayments?: components["schemas"]["SectionResponseListUpcomingPayment"];
            yearToDate?: components["schemas"]["SectionResponseListCurrencySummary"];
        };
        EvolutionPointResponse: {
            cost?: components["schemas"]["MoneyView"];
            /** Format: date */
            date?: string;
            marketValue?: components["schemas"]["MoneyView"];
        };
        FeeRowResponse: {
            amount?: components["schemas"]["MoneyView"];
            ivaTreatment?: string;
            label?: string;
            pct?: number;
            scope?: string;
        };
        FeesSummaryResponse: {
            accounts?: components["schemas"]["FeeRowResponse"][];
            brokers?: components["schemas"]["FeeRowResponse"][];
            cards?: components["schemas"]["FeeRowResponse"][];
            debitCreditTaxRate?: number;
        };
        FilterOptionsResponse: {
            accounts?: components["schemas"]["AccountOptionResponse"][];
            categories?: components["schemas"]["CategoryOptionResponse"][];
            methods?: string[];
        };
        FlowPointResponse: {
            expense?: components["schemas"]["MoneyView"];
            income?: components["schemas"]["MoneyView"];
            month?: string;
        };
        ImportHealthRowResponse: {
            alias?: string;
            cbu?: string;
            /** Format: int64 */
            daysSince?: number;
            /** Format: date-time */
            lastImportAt?: string;
            status?: string;
        };
        ImportRunRowResponse: {
            accountCbu?: string;
            /** Format: int32 */
            duplicates?: number;
            /** Format: int32 */
            failed?: number;
            fileName?: string;
            /** Format: date-time */
            importedAt?: string;
            /** Format: int32 */
            inserted?: number;
            /** Format: int64 */
            runId?: number;
            status?: string;
        };
        ImportsBffResponse: {
            activeRun?: components["schemas"]["SectionResponseActiveRunResponse"];
            history?: components["schemas"]["SectionResponseListImportRunRowResponse"];
            reconciliation?: components["schemas"]["SectionResponseListReconciliationRowResponse"];
        };
        InvestmentsBffResponse: {
            alerts?: components["schemas"]["SectionResponseListAlertRowResponse"];
            composition?: components["schemas"]["SectionResponseListCompositionSliceResponse"];
            evolution?: components["schemas"]["SectionResponseListEvolutionPointResponse"];
            kpis?: components["schemas"]["SectionResponseInvestmentsKpisResponse"];
            marketStrip?: components["schemas"]["SectionResponseListMarketQuoteResponse"];
            positions?: components["schemas"]["SectionResponseListPositionRowResponse"];
            recentOperations?: components["schemas"]["SectionResponseListOperationRowResponse"];
        };
        InvestmentsKpisResponse: {
            cost?: components["schemas"]["MoneyView"];
            marketValue?: components["schemas"]["MoneyView"];
            pnl?: components["schemas"]["MoneyView"];
            pnlPct?: number;
        };
        Loan: {
            active?: boolean;
            currency?: string;
            /** Format: int64 */
            id?: number;
            name?: string;
            principal?: string;
            /** Format: int32 */
            remainingInstallments?: number;
            /** Format: int32 */
            totalInstallments?: number;
        };
        LoanRowResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            installmentsPaid?: number;
            /** Format: int32 */
            installmentsTotal?: number;
            label?: string;
            /** Format: date */
            nextInstallmentDate?: string;
            outstanding?: components["schemas"]["MoneyView"];
            principal?: number;
        };
        MarketQuoteResponse: {
            code?: string;
            label?: string;
            /** Format: date-time */
            observedAt?: string;
            unit?: string;
            value?: number;
            variation?: number;
        };
        MoneyView: {
            amount: string;
            currency: string;
            secondary?: components["schemas"]["MoneyView"];
        };
        NetWorthDeltaResponse: {
            amount?: components["schemas"]["MoneyView"];
            pct?: number;
        };
        NetWorthPointResponse: {
            /** Format: date */
            date?: string;
            value?: components["schemas"]["MoneyView"];
        };
        NetWorthResponse: {
            allTimeHigh?: boolean;
            delta?: components["schemas"]["NetWorthDeltaResponse"];
            series?: components["schemas"]["NetWorthPointResponse"][];
        };
        NotificationPreferenceResponse: {
            category?: string;
            channels?: string[];
        };
        OperationRowResponse: {
            amount?: components["schemas"]["MoneyView"];
            /** Format: date */
            date?: string;
            /** Format: int64 */
            holdingId?: number;
            kind?: string;
            quantity?: number;
            ticker?: string;
        };
        OverviewBffResponse: {
            breakdown?: components["schemas"]["SectionResponseBreakdownResponse"];
            committed?: components["schemas"]["SectionResponseListCommittedPointResponse"];
            flow?: components["schemas"]["SectionResponseListFlowPointResponse"];
            kpis?: components["schemas"]["SectionResponseOverviewKpisResponse"];
            latestMovements?: components["schemas"]["SectionResponseListTransactionRowResponse"];
            netWorth?: components["schemas"]["SectionResponseNetWorthResponse"];
            spendByCategory?: components["schemas"]["SectionResponseListCategorySpendResponse"];
            upcomingPayments?: components["schemas"]["SectionResponseListUpcomingPaymentResponse"];
        };
        OverviewKpisResponse: {
            cash: components["schemas"]["MoneyView"];
            committed: components["schemas"]["MoneyView"];
            expense: components["schemas"]["MoneyView"];
            income: components["schemas"]["MoneyView"];
        };
        PositionRowResponse: {
            avgCost?: components["schemas"]["MoneyView"];
            bankNumber?: string;
            /** Format: int64 */
            holdingId?: number;
            marketValue?: components["schemas"]["MoneyView"];
            name?: string;
            pnl?: components["schemas"]["MoneyView"];
            pnlPct?: number;
            price?: components["schemas"]["MoneyView"];
            quantity?: number;
            ticker?: string;
        };
        ReconciliationRowResponse: {
            computedBalance?: components["schemas"]["MoneyView"];
            expectedBalance?: components["schemas"]["MoneyView"];
            matches?: boolean;
            /** Format: int64 */
            runId?: number;
        };
        RuleRowResponse: {
            /** Format: int64 */
            categoryId?: number;
            categoryName?: string;
            /** Format: int64 */
            id?: number;
            matcher?: string;
            /** Format: int32 */
            priority?: number;
        };
        SearchBffResponse: {
            categories?: components["schemas"]["SectionResponseListSearchHitResponse"];
            movements?: components["schemas"]["SectionResponseListSearchHitResponse"];
            positions?: components["schemas"]["SectionResponseListSearchHitResponse"];
        };
        SearchHitResponse: {
            href?: string;
            id?: string;
            label?: string;
            sublabel?: string;
        };
        SectionResponseActiveRunResponse: {
            data?: components["schemas"]["ActiveRunResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseBanksKpisResponse: {
            data?: components["schemas"]["BanksKpisResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseBreakdownResponse: {
            data?: components["schemas"]["BreakdownResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseCategoriesKpisResponse: {
            data?: components["schemas"]["CategoriesKpisResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseCategoryTrendResponse: {
            data?: components["schemas"]["CategoryTrendResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseFeesSummaryResponse: {
            data?: components["schemas"]["FeesSummaryResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseFilterOptionsResponse: {
            data?: components["schemas"]["FilterOptionsResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseInvestmentsKpisResponse: {
            data?: components["schemas"]["InvestmentsKpisResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListAccountRowResponse: {
            data?: components["schemas"]["AccountRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListAlertRowResponse: {
            data?: components["schemas"]["AlertRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListBudgetRowResponse: {
            data?: components["schemas"]["BudgetRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCalendarEntryResponse: {
            data?: components["schemas"]["CalendarEntryResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCardRowResponse: {
            data?: components["schemas"]["CardRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCategorySpendResponse: {
            data?: components["schemas"]["CategorySpendResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCommittedPointResponse: {
            data?: components["schemas"]["CommittedPointResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCompositionSliceResponse: {
            data?: components["schemas"]["CompositionSliceResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListCurrencySummary: {
            items?: components["schemas"]["CurrencySummary"][];
            /** Format: date-time */
            observedAt?: string;
            status?: string;
        };
        SectionResponseListEvolutionPointResponse: {
            data?: components["schemas"]["EvolutionPointResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListFlowPointResponse: {
            data?: components["schemas"]["FlowPointResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListImportHealthRowResponse: {
            data?: components["schemas"]["ImportHealthRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListImportRunRowResponse: {
            data?: components["schemas"]["ImportRunRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListLoan: {
            items?: components["schemas"]["Loan"][];
            /** Format: date-time */
            observedAt?: string;
            status?: string;
        };
        SectionResponseListLoanRowResponse: {
            data?: components["schemas"]["LoanRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListMarketQuoteResponse: {
            data?: components["schemas"]["MarketQuoteResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListNotificationPreferenceResponse: {
            data?: components["schemas"]["NotificationPreferenceResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListOperationRowResponse: {
            data?: components["schemas"]["OperationRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListPositionRowResponse: {
            data?: components["schemas"]["PositionRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListReconciliationRowResponse: {
            data?: components["schemas"]["ReconciliationRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListRuleRowResponse: {
            data?: components["schemas"]["RuleRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListSearchHitResponse: {
            data?: components["schemas"]["SearchHitResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListSessionRowResponse: {
            data?: components["schemas"]["SessionRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListTransactionRowResponse: {
            data?: components["schemas"]["TransactionRowResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseListUpcomingPayment: {
            items?: components["schemas"]["UpcomingPayment"][];
            /** Format: date-time */
            observedAt?: string;
            status?: string;
        };
        SectionResponseListUpcomingPaymentResponse: {
            data?: components["schemas"]["UpcomingPaymentResponse"][];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseNetWorthResponse: {
            data?: components["schemas"]["NetWorthResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseOverviewKpisResponse: {
            data?: components["schemas"]["OverviewKpisResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseTransactionDetailResponse: {
            data?: components["schemas"]["TransactionDetailResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseTransactionsPageResponse: {
            data?: components["schemas"]["TransactionsPageResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseTransactionsSummaryResponse: {
            data?: components["schemas"]["TransactionsSummaryResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseUncategorisedSummaryResponse: {
            data?: components["schemas"]["UncategorisedSummaryResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseUserPreferencesResponse: {
            data?: components["schemas"]["UserPreferencesResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SectionResponseUserProfileResponse: {
            data?: components["schemas"]["UserProfileResponse"];
            /** Format: date-time */
            observedAt: string;
            status: string;
        };
        SessionRowResponse: {
            current?: boolean;
            device?: string;
            id?: string;
            ip?: string;
            /** Format: date-time */
            lastSeenAt?: string;
        };
        SettingsBffResponse: {
            fees?: components["schemas"]["SectionResponseFeesSummaryResponse"];
            notificationPrefs?: components["schemas"]["SectionResponseListNotificationPreferenceResponse"];
            preferences?: components["schemas"]["SectionResponseUserPreferencesResponse"];
            profile?: components["schemas"]["SectionResponseUserProfileResponse"];
            sessions?: components["schemas"]["SectionResponseListSessionRowResponse"];
        };
        TransactionDetailBffResponse: {
            detail?: components["schemas"]["SectionResponseTransactionDetailResponse"];
        };
        TransactionDetailResponse: {
            origin?: components["schemas"]["TransactionOriginResponse"];
            transaction?: components["schemas"]["TransactionRowResponse"];
        };
        TransactionOriginResponse: {
            fileName?: string;
            /** Format: date-time */
            importedAt?: string;
            reconciled?: boolean;
            /** Format: int64 */
            runId?: number;
        };
        TransactionRowResponse: {
            accountAlias?: string;
            accountCbu?: string;
            amount?: components["schemas"]["MoneyView"];
            /** Format: int64 */
            categoryId?: number;
            categoryName?: string;
            /** Format: date */
            date?: string;
            description?: string;
            direction?: string;
            /** Format: int64 */
            id?: number;
            method?: string;
            note?: string;
        };
        TransactionsBffResponse: {
            filterOptions?: components["schemas"]["SectionResponseFilterOptionsResponse"];
            page?: components["schemas"]["SectionResponseTransactionsPageResponse"];
            summary?: components["schemas"]["SectionResponseTransactionsSummaryResponse"];
            uncategorised?: components["schemas"]["SectionResponseUncategorisedSummaryResponse"];
        };
        TransactionsPageResponse: {
            /** Format: int32 */
            page?: number;
            rows?: components["schemas"]["TransactionRowResponse"][];
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        TransactionsSummaryResponse: {
            /** Format: int64 */
            count?: number;
            expense?: components["schemas"]["MoneyView"];
            income?: components["schemas"]["MoneyView"];
            net?: components["schemas"]["MoneyView"];
        };
        UncategorisedSummaryResponse: {
            /** Format: int64 */
            count?: number;
        };
        UpcomingPayment: {
            amount?: string;
            currency?: string;
            description?: string;
            /** Format: date */
            dueDate?: string;
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            installmentNumber?: number;
            paid?: boolean;
            /** Format: int32 */
            totalInstallments?: number;
            type?: string;
        };
        UpcomingPaymentResponse: {
            amount?: components["schemas"]["MoneyView"];
            /** Format: date */
            dueDate?: string;
            id?: string;
            kind?: string;
            label?: string;
        };
        UserPreferencesResponse: {
            /** Format: int32 */
            decimals?: number;
            numberFormat?: string;
            primaryCurrency?: string;
            secondaryCurrency?: string;
            useGainLossColors?: boolean;
        };
        UserProfileResponse: {
            /** Format: date-time */
            createdAt?: string;
            email?: string;
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBanks: {
        parameters: {
            query?: {
                currency?: string;
                secondary?: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBanksBffResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: {
                currency?: string;
                secondary?: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoriesBffResponse"];
                };
            };
        };
    };
    getCurrencies: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAvailableCurrenciesResponse"];
                };
            };
        };
    };
    getImports: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseImportsBffResponse"];
                };
            };
        };
    };
    getInvestments: {
        parameters: {
            query?: {
                currency?: string;
                secondary?: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInvestmentsBffResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: {
                currency?: string;
                secondary?: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOverviewBffResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSearchBffResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSettingsBffResponse"];
                };
            };
        };
    };
    getTransactions: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                categories?: string[];
                accounts?: string[];
                from?: string;
                to?: string;
                currency?: string;
                secondary?: string;
            };
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionsBffResponse"];
                };
            };
        };
    };
    getTransactionDetail: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": number;
            };
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTransactionDetailBffResponse"];
                };
            };
        };
    };
    data: {
        parameters: {
            query?: never;
            header: {
                "X-User-Id": number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponse"];
                };
            };
        };
    };
}
